### ISSUE TITLE
uninitialized constant WuParty::MultiJson

### ISSUE THREAD

**Issue by BenKnigge** [seven1m/wuparty#17]
Using ruby 2.2.1 I'm getting the error "uninitialized constant WuParty::MultiJson"

When attempting to make any call.

Here's a portion of the stack trace if it's helpful

/home/xxx/.rvm/gems/ruby-2.2.1/gems/wuparty-1.2.6/lib/wuparty.rb:186:in `rescue in handle_http_verb': uninitialized constant WuParty::MultiJson (NameError)
    from /home/xxx/.rvm/gems/ruby-2.2.1/gems/wuparty-1.2.6/lib/wuparty.rb:184:in`handle_http_verb'
    from /home/xxx/.rvm/gems/ruby-2.2.1/gems/wuparty-1.2.6/lib/wuparty.rb:159:in `get'
    from /home/xxx/.rvm/gems/ruby-2.2.1/gems/wuparty-1.2.6/lib/wuparty.rb:138:in`form'

**Comment by seven1m** [comment]
I just tested this locally and everything seems to be working.

Can you try upgrading the gem multipart-post and try again?

`gem install multipart-post` or `bundle update multipart-post` if using Bundler.

**Comment by BenKnigge** [comment]
I'm using Using multipart-post 2.0.0

Here's how I'm calling

wufoo = WuParty.new($wufoo_user_email, $wufoo_api_key)

form = wufoo.form('lead-generator')

which results in the error.


On Wed, Jan 6, 2016 at 3:18 PM, Tim Morgan <notifications@github.com> wrote:
> I just tested this locally and everything seems to be working.
>
> Can you try upgrading the gem multipart-post and try again?
>
> gem install multipart-post or bundle update multipart-post if using Bundler.
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Benjamin Knigge
Ben@Heptec.com
tel: +1-310-570-2880

**Comment by BenKnigge** [comment]
The end point constant is incorrect in my case as my client registered with wufoo.eu

line 93

ENDPOINT    = 'https://%s.wufoo.com/api/v3'

I'd like to propose making the end point a parameter with the default value being wufoo.com in any future release.

**Comment by BenKnigge** [comment]
The base URL in my case is also incorrect the value of @account in my case is xxx.com where xxx is the  clients domain but the base_url should be the ENDPOINT % site without the domain extension .com. base_url should be a parameter.

**Comment by seven1m** [comment]
Awesome. I don't personally use this library any more, but I'll gladly accept Pull Requests if you want to make it better!

**Comment by BenKnigge** [comment]
Request has been made.
