### ISSUE TITLE
Wuparty breaks newest version of HTTParty

### ISSUE THREAD

**Issue by peritpatrio** [seven1m/wuparty#19]
- HTTParty gem [added support for multipart in version 0.16.0](https://github.com/jnunemaker/httparty/blob/v0.16.0/Changelog.md#0160)
- HTTParty is being modified by wuparty to support multipart here: https://github.com/seven1m/wuparty/blob/master/lib/wuparty.rb#L7

**Comment by seven1m** [comment]
Fixed and released as 1.3.0
